name: Moon CI
on:
  push:
    branches:
      - main
  pull_request: {}
env:
  GIT_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
jobs:
  ci:
    name: Moon CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Moon CI
        uses: ./.github/actions/moon-ci-setup
