/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CodeownersOrderBy = "file-source" | "project-name";
export type HasherOptimization = "accuracy" | "performance";
export type HasherWalkStrategy = "glob" | "vcs";
export type PartialWorkspaceProjects =
  | PartialWorkspaceProjectsConfig
  | string[]
  | {
      [k: string]: string;
    };
export type VcsManager = "git";
export type VcsProvider = "bitbucket" | "github" | "gitlab" | "other";

/**
 * Docs: https://moonrepo.dev/docs/config/workspace
 */
export interface PartialWorkspaceConfig {
  $schema?: string | null;
  codeowners?: PartialCodeownersConfig | null;
  constraints?: PartialConstraintsConfig | null;
  experiments?: PartialExperimentsConfig | null;
  extends?: string | null;
  generator?: PartialGeneratorConfig | null;
  hasher?: PartialHasherConfig | null;
  notifier?: PartialNotifierConfig | null;
  projects?: PartialWorkspaceProjects | null;
  runner?: PartialRunnerConfig | null;
  telemetry?: boolean | null;
  vcs?: PartialVcsConfig | null;
  versionConstraint?: string | null;
}
export interface PartialCodeownersConfig {
  globalPaths?: {
    [k: string]: string[];
  } | null;
  orderBy?: CodeownersOrderBy | null;
  syncOnRun?: boolean | null;
}
export interface PartialConstraintsConfig {
  enforceProjectTypeRelationships?: boolean | null;
  tagRelationships?: {
    [k: string]: string[];
  } | null;
}
export interface PartialExperimentsConfig {
  taskOutputBoundaries?: boolean | null;
}
export interface PartialGeneratorConfig {
  templates?: string[] | null;
}
export interface PartialHasherConfig {
  batchSize?: number | null;
  ignoreMissingPatterns?: string[] | null;
  ignorePatterns?: string[] | null;
  optimization?: HasherOptimization | null;
  walkStrategy?: HasherWalkStrategy | null;
  warnOnMissingInputs?: boolean | null;
}
export interface PartialNotifierConfig {
  webhookUrl?: string | null;
}
export interface PartialWorkspaceProjectsConfig {
  globs?: string[] | null;
  sources?: {
    [k: string]: string;
  } | null;
}
export interface PartialRunnerConfig {
  archivableTargets?: string[] | null;
  cacheLifetime?: string | null;
  inheritColorsForPipedTasks?: boolean | null;
  logRunningCommand?: boolean | null;
}
export interface PartialVcsConfig {
  defaultBranch?: string | null;
  hooks?: {
    [k: string]: string[];
  } | null;
  manager?: VcsManager | null;
  provider?: VcsProvider | null;
  remoteCandidates?: string[] | null;
  syncHooks?: boolean | null;
}

export default PartialWorkspaceConfig;
