/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/

export type ArrowParensConfig = ("always" | "avoid")
export type EmbeddedLanguageFormattingConfig = ("auto" | "off")
export type EndOfLineConfig = ("lf" | "crlf" | "cr")
export type SortOrderConfig = ("asc" | "desc")
export type ObjectWrapConfig = ("preserve" | "collapse" | "always")
export type QuotePropsConfig = ("as-needed" | "consistent" | "preserve")
export type TrailingCommaConfig = ("all" | "es5" | "none")

/**
 * Configuration options for the Oxfmt.
 * 
 * Most options are the same as Prettier's options.
 * See also <https://prettier.io/docs/options>
 * 
 * In addition, some options are our own extensions.
 */
export interface Oxfmtrc {
/**
 * Include parentheses around a sole arrow function parameter. (Default: `"always"`)
 */
arrowParens?: (ArrowParensConfig | null)
/**
 * Put the `>` of a multi-line JSX element at the end of the last line
 * instead of being alone on the next line. (Default: `false`)
 */
bracketSameLine?: (boolean | null)
/**
 * Print spaces between brackets in object literals. (Default: `true`)
 */
bracketSpacing?: (boolean | null)
/**
 * Control whether formats quoted code embedded in the file. (Default: `"auto"`)
 */
embeddedLanguageFormatting?: (EmbeddedLanguageFormattingConfig | null)
/**
 * Which end of line characters to apply. (Default: `"lf"`)
 */
endOfLine?: (EndOfLineConfig | null)
/**
 * Experimental: Sort import statements. Disabled by default.
 */
experimentalSortImports?: (SortImportsConfig | null)
/**
 * Experimental: Sort `package.json` keys. (Default: `true`)
 */
experimentalSortPackageJson?: (boolean | null)
/**
 * Ignore files matching these glob patterns. Current working directory is used as the root.
 */
ignorePatterns?: (string[] | null)
/**
 * Whether to insert a final newline at the end of the file. (Default: `true`)
 */
insertFinalNewline?: (boolean | null)
/**
 * Use single quotes instead of double quotes in JSX. (Default: `false`)
 */
jsxSingleQuote?: (boolean | null)
/**
 * How to wrap object literals when they could fit on one line or span multiple lines. (Default: `"preserve"`)
 * NOTE: In addition to Prettier's `"preserve"` and `"collapse"`, we also support `"always"`.
 */
objectWrap?: (ObjectWrapConfig | null)
/**
 * The line length that the printer will wrap on. (Default: `100`)
 */
printWidth?: (number | null)
/**
 * Change when properties in objects are quoted. (Default: `"as-needed"`)
 */
quoteProps?: (QuotePropsConfig | null)
/**
 * Print semicolons at the ends of statements. (Default: `true`)
 */
semi?: (boolean | null)
/**
 * Put each attribute on a new line in JSX. (Default: `false`)
 */
singleAttributePerLine?: (boolean | null)
/**
 * Use single quotes instead of double quotes. (Default: `false`)
 */
singleQuote?: (boolean | null)
/**
 * Number of spaces per indentation level. (Default: `2`)
 */
tabWidth?: (number | null)
/**
 * Print trailing commas wherever possible. (Default: `"all"`)
 */
trailingComma?: (TrailingCommaConfig | null)
/**
 * Use tabs for indentation or spaces. (Default: `false`)
 */
useTabs?: (boolean | null)
[k: string]: unknown | undefined
}
export interface SortImportsConfig {
/**
 * Custom groups configuration for organizing imports.
 * Each array element represents a group, and multiple group names in the same array are treated as one.
 * Accepts both `string` and `string[]` as group elements.
 */
groups?: (string[][] | null)
/**
 * Ignore case when sorting. (Default: `true`)
 */
ignoreCase?: (boolean | null)
/**
 * Glob patterns to identify internal imports.
 */
internalPattern?: (string[] | null)
/**
 * Add newlines between import groups. (Default: `true`)
 */
newlinesBetween?: (boolean | null)
/**
 * Sort order. (Default: `"asc"`)
 */
order?: (SortOrderConfig | null)
/**
 * Partition imports by comments. (Default: `false`)
 */
partitionByComment?: (boolean | null)
/**
 * Partition imports by newlines. (Default: `false`)
 */
partitionByNewline?: (boolean | null)
/**
 * Sort side-effect imports. (Default: `false`)
 */
sortSideEffects?: (boolean | null)
[k: string]: unknown | undefined
}

export type { Oxfmtrc as default };
