/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PartialBinEntry = string | PartialBinConfig;
export type NodeProjectAliasFormat = "name-and-scope" | "name-only";
export type NodeVersionFormat =
  | "file"
  | "link"
  | "star"
  | "version"
  | "version-caret"
  | "version-tilde"
  | "workspace"
  | "workspace-caret"
  | "workspace-tilde";
export type NodePackageManager = "npm" | "pnpm" | "yarn";
export type NodeVersionManager = "nodenv" | "nvm";

/**
 * Docs: https://moonrepo.dev/docs/config/toolchain
 */
export interface PartialToolchainConfig {
  $schema?: string | null;
  deno?: PartialDenoConfig | null;
  extends?: string | null;
  node?: PartialNodeConfig | null;
  rust?: PartialRustConfig | null;
  typescript?: PartialTypeScriptConfig | null;
}
/**
 * Docs: https://moonrepo.dev/docs/config/toolchain#deno
 */
export interface PartialDenoConfig {
  bins?: PartialBinEntry[] | null;
  depsFile?: string | null;
  lockfile?: boolean | null;
}
export interface PartialBinConfig {
  bin?: string | null;
  force?: boolean | null;
  local?: boolean | null;
  name?: string | null;
}
/**
 * Docs: https://moonrepo.dev/docs/config/toolchain#node
 */
export interface PartialNodeConfig {
  addEnginesConstraint?: boolean | null;
  aliasPackageNames?: NodeProjectAliasFormat | null;
  binExecArgs?: string[] | null;
  dedupeOnLockfileChange?: boolean | null;
  dependencyVersionFormat?: NodeVersionFormat | null;
  inferTasksFromScripts?: boolean | null;
  npm?: PartialNpmConfig | null;
  packageManager?: NodePackageManager | null;
  pnpm?: PartialPnpmConfig | null;
  syncProjectWorkspaceDependencies?: boolean | null;
  syncVersionManagerConfig?: NodeVersionManager | null;
  version?: string | null;
  yarn?: PartialYarnConfig | null;
}
export interface PartialNpmConfig {
  version?: string | null;
}
export interface PartialPnpmConfig {
  version?: string | null;
}
export interface PartialYarnConfig {
  plugins?: string[] | null;
  version?: string | null;
}
/**
 * Docs: https://moonrepo.dev/docs/config/toolchain#rust
 */
export interface PartialRustConfig {
  bins?: PartialBinEntry[] | null;
  syncToolchainConfig?: boolean | null;
  version?: string | null;
}
/**
 * Docs: https://moonrepo.dev/docs/config/toolchain#typescript
 */
export interface PartialTypeScriptConfig {
  createMissingConfig?: boolean | null;
  projectConfigFileName?: string | null;
  rootConfigFileName?: string | null;
  rootOptionsConfigFileName?: string | null;
  routeOutDirToCache?: boolean | null;
  syncProjectReferences?: boolean | null;
  syncProjectReferencesToPaths?: boolean | null;
}

export default PartialToolchainConfig;
