import {
  SymlinkTarget,
  type AutoLinkConfig,
} from "@condu/types/configTypes.js";
import {
  CONDU_CONFIG_FILE_NAME,
  CONDU_CONFIG_DIR_NAME,
} from "@condu/types/constants.js";
import { defineFeature } from "condu/defineFeature.js";
import * as path from "node:path";
import * as fs from "node:fs/promises";
import { match, P } from "ts-pattern";

export const autolink = ({ mapping, ignore = [] }: AutoLinkConfig = {}) =>
  defineFeature({
    name: "autolink",
    order: { priority: "end" },
    actionFn: async (config, state) => {
      const entries = await fs.readdir(config.configDir, {
        withFileTypes: true,
      });
      const allIgnores = [
        CONDU_CONFIG_FILE_NAME,
        ...ignore,
        ...state.autolinkIgnore,
      ];
      const configFiles = entries
        .filter(
          (entry) =>
            entry.isFile() &&
            !allIgnores.some((i) =>
              typeof i === "object"
                ? i.test(entry.name)
                : path.normalize(i) === entry.name,
            ),
        )
        .map((entry) => entry.name);

      return {
        effects: [
          {
            files: configFiles.map((filename) => {
              const targetName = mapping?.[filename] ?? filename;
              const extension = path.extname(filename);
              return {
                path: targetName,
                content: match(extension)
                  .returnType<string | SymlinkTarget>()
                  .with(
                    P.union(".ts", ".js"),
                    () =>
                      `/* eslint-disable */
// This file is auto-generated by the autolink feature.
// Do not edit this file directly - see the file it re-exports from:
// @ts-ignore
export * from "./${CONDU_CONFIG_DIR_NAME}/${filename}";`,
                  )
                  .otherwise(
                    () =>
                      new SymlinkTarget(
                        `./${CONDU_CONFIG_DIR_NAME}/${filename}`,
                      ),
                  ),
              };
            }),
          },
        ],
      };
    },
  });
