import type { PartialProjectConfig, PartialTaskConfig } from "@moonrepo/types";
import type { PackageJson } from "@condu/schema-types/schemas/packageJson.gen.js";
import type { Pattern } from "ts-pattern";
import type { CONFIGURED } from "./configure.js";
import type { ProjectManifest } from "@pnpm/types";

export interface DependencyDef {
  packageAlias: string;
  versionOrTag?: string;
  target?: "dependencies" | "devDependencies" | "optionalDependencies";
  skipIfExists?: boolean;
  /** to what extent should this dependency be managed by condu? */
  managed?: ManagedDependencyConfig | false;
}

export interface Task {
  // TODO: allow matching which package the task belongs to, like with Files (matchPackage)
  name: string;
  // format is any transformation in-place
  type: "test" | "build" | "publish" | "format" | "start";
  definition: PartialTaskConfig;
}

export type GetExistingContentFn = <T extends string | object>(
  defaultFallback?: T | undefined,
) => Promise<T | undefined> | T | undefined;

export class SymlinkTarget {
  toString() {
    return `symlink:${this.target}`;
  }
  constructor(public readonly target: string) {}
}

type AnyObject = {
  readonly [key: string]: any;

  // without this dummy property below, TypeScript will widen to 'any':
  _?: string;
};

export type FileContent = string | AnyObject | Array<object> | SymlinkTarget;

export interface FileDef {
  /**
   * should this file be ephemeral and is always regenerated by the apply tool (default),
   * or should it be committed?
   * will affect the behavior for features like gitignore
   **/
  type?: "ephemeral" | "committed" | "ignore-only";
  /**
   * always overwrite the file, even if it was changed by the user
   * CAREFUL: this *will* overwrite user changes without warning
   */
  alwaysOverwrite?: boolean;
  /** should this file be published when making a distributable package */
  publish?: boolean;
  /**
   * if you need to access 'state' (e.g. to list all files or tasks),
   * using a function is preferable, as it will be executed *after* all the state had been collected,
   * rather than during its collection, as is the case with pure string or object.
   *
   * if returned an object, the correct stringifier is chosen based on the file extension
   * if a string is returned, it will be written as-is
   **/
  content?:
    | FileContent
    | ((opts: {
        pkg: WorkspacePackage;
        getExistingContentAndMarkAsUserEditable: GetExistingContentFn;
      }) => Promise<FileContent> | FileContent);
  path: string;
}

export type ManagedDependencyConfig = "presence" | "version";

export interface PackageJsonConduSection
  extends Pick<
    PartialProjectConfig,
    "language" | "platform" | "tags" | "type" | "stack"
  > {
  initialDevelopment?: boolean;
  managedDependencies?: Record<string, ManagedDependencyConfig>;
  defaultScope?: string;
}

export interface ConduPackageJson extends PackageJson {
  // name is mandatory
  name: string;
  condu?: PackageJsonConduSection;

  bolt?: { workspaces?: string[] };
  pnpm?: ProjectManifest["pnpm"];
  resolutions?: Record<string, string>;
  overrides?: Record<string, string>;
}

export interface CollectedTaskDef extends Task {
  featureName: string;
  target: ConduPackageJson;
}

export interface CollectedFileDef extends FileDef {
  featureName: string;
  /**
   * set to true if the file should not be ignored,
   * or list the feature names by which it should be ignored
   *
   * prefer to use type: 'committed' instead, this is used internally
   **/
  skipIgnore?: boolean | string[];
  targetDir: string;
  targetPackage: WorkspacePackage;
}

export type EntrySources = Record<
  string,
  {
    types?: string;
    source?: string;
    bun?: string;
    import?: string;
    require?: string;
    default?: string;
  }
>;

export interface Hooks {
  modifyPublishPackageJson: (
    packageJson: PackageJson,
  ) => PackageJson | Promise<PackageJson>;
  modifyEntrySourcesForRelease: (
    entrySources: EntrySources,
  ) => EntrySources | Promise<EntrySources>;
}

export interface CollectedState {
  /** these files will be created during execution */
  files: CollectedFileDef[];
  /** we'll ensure these dependencies are installed during execution */
  devDependencies: (string | DependencyDef)[];
  resolutions: Record<string, string>;
  tasks: CollectedTaskDef[];
  hooksByPackage: {
    [packageName: string]: Partial<Hooks>;
  };
}

export interface StateFlags {
  preventAdditionalTasks?: boolean;
}

export type ToIntermediateState<T> = {
  [P in keyof T]?: T[P] extends Array<infer O>
    ? ReadonlyArray<O | false | undefined>
    : T[P];
};

export type Effects = {
  /** these files will be created during execution */
  files?: ReadonlyArray<FileDef | false | undefined>;
  tasks?: ReadonlyArray<Task | false | undefined>;
  hooks?: Partial<Hooks>;

  /** we'll ensure these dependencies are installed during execution */
  devDependencies?: (string | DependencyDef)[];

  /** we'll ensure these dependency resolutions are applied */
  resolutions?: Record<string, string>;

  /**
   * ts-pattern for package.jsons that the state applies to. Defaults to workspace.
   * @default { kind: "workspace" }
   * */
  matchPackage?: Pattern.Pattern<WorkspacePackage> | Partial<WorkspacePackage>;
};

export interface FeatureResult {
  effects?: (Effects | null | undefined | false)[];
  flags?: ReadonlyArray<keyof StateFlags>;
}

export type FeatureActionFn = (
  config: ConduConfigWithInferredValuesAndProject,
  /**
   * TODO: consider lifting 'state' argument to 'content' function of files
   * since the state here is only "collected till now"
   **/
  state: CollectedState,
) => FeatureResult | Promise<FeatureResult | void> | void;

export interface FeatureDefinition {
  actionFn: FeatureActionFn;
  name: string;
  order?: {
    after?: Array<string>;
    priority?: "beginning" | "end";
  };
}

export interface Conventions {
  /** @default '.' */
  sourceDir?: string;
  sourceExtensions?: string[];
  buildDir?: string;
  /** @default ['.gen', '.generated'] */
  generatedSourceFileNameSuffixes?: string[];
}

export interface ResolvedConventionsWithWorkspace
  extends Required<Conventions> {
  projectConventions?: WorkspaceProjectDefined[];
}

type GitConfig = {
  /** inferred from git if empty */
  defaultBranch?: string;
};

type NodeConfig = {
  /** @default 'yarn' */
  packageManager?: {
    name: "yarn" | "npm" | "pnpm" | "bun";
    version?: string;
  };
  version?: string;
};

type Engine = "node" | "bun";

export interface AutoLinkConfig {
  /** remap file names, key is the filename in .config/, value is the target name */
  mapping?: Record<string, string>;
  ignore?: (string | RegExp)[];
}

export interface ConduConfig {
  /** primary engine used to run the tool */
  engine?: Engine;
  node?: NodeConfig;
  publish?: {
    registry?: string;
    access?: "public" | "restricted";
  };
  git?: GitConfig;
  features: FeatureDefinition[];
  /** automatically links any config file inside .config/ folder to the root directory and makes it invisible */
  autolink?: boolean | AutoLinkConfig;
  /** when present, assumes monorepo */
  projects?: WorkspaceProjectsConvention[];
  conventions?: Conventions;
}

export interface ConfiguredConduConfig extends ConduConfig {
  [CONFIGURED]: true;
}

export type GetConduConfigPromise = (
  pkg: IPackageEntry,
) => Promise<ConfiguredConduConfig>;

export type ConduConfigInput =
  | ConduConfig
  | ((pkg: IPackageEntry) => ConduConfig)
  | ((pkg: IPackageEntry) => Promise<ConduConfig>);

export type ConduConfigDefaultExport =
  | ConfiguredConduConfig
  | ((pkg: IPackageEntry) => ConfiguredConduConfig)
  | ((pkg: IPackageEntry) => Promise<ConfiguredConduConfig>);

export interface ConduConfigWithInferredValues extends ConfiguredConduConfig {
  // TODO: add error / warning functions
  /** absolute path to the workspace */
  workspaceDir: string;
  /** absolute path to the config directory */
  configDir: string;
  conventions: ResolvedConventionsWithWorkspace;
  git: Required<GitConfig>;
  node: Required<NodeConfig>;
  engine: Engine;
}

export interface Project extends WorkspaceRootPackage {
  projectConventions?: WorkspaceProjectDefined[];
  config: ConduConfigWithInferredValues;
  getWorkspacePackages: () => Promise<readonly WorkspaceSubPackage[]>;
}

export interface ConduConfigWithInferredValuesAndProject
  extends ConduConfigWithInferredValues {
  project: Project;
}

export interface LoadConfigOptions {
  startDir?: string;
  throwOnManualChanges?: boolean;
}

export interface WriteManifestFnOptions {
  force?: boolean;
  merge?: boolean;
}

export type WriteManifestFn = (
  manifest: ConduPackageJson | PackageJson,
  options?: WriteManifestFnOptions,
) => Promise<void>;

export interface WorkspacePackage extends IPackageEntry {
  kind: "workspace" | "package";
}

export interface WorkspaceRootPackage extends WorkspacePackage {
  kind: "workspace";
}

export interface WorkspaceSubPackage extends WorkspacePackage {
  kind: "package";
}

export interface IPackageEntry {
  /** shortcut to manifest.name */
  name: string;
  scope?: string;
  scopedName?: string;
  manifest: ConduPackageJson;
  manifestRelPath: string;
  manifestAbsPath: string;
  /** relative directory of the package from the workspace path */
  relPath: string;
  /** absolute directory of the package */
  absPath: string;
  writeProjectManifest: WriteManifestFn;
}

export interface ProjectConventionConfig {
  private?: boolean;

  /**
   * path to the template folder that will be used
   * to bootstrap packages created using the convention
   *
   * @default `../@template`
   **/
  templatePath?: string;
}

export interface ParentDirectoryProjectConvention
  extends ProjectConventionConfig {
  /**
   * defines how the name should be created from the project directory name.
   * '*' in the string refers to the project directory name
   * @example when '@condu/*' will name the project '@condu/utils' if the project folder is 'utils'
   * @default '*'
   **/
  nameConvention?: string;
  /**
   * defines the path to the project directory
   * @example when set to 'packages/tools' will expect that packages will live in the 'packages/tools' directory
   **/
  parentPath: string;
}

export interface ExplicitPathProjectConvention extends ProjectConventionConfig {
  path: string;
  name?: string;
}

export type WorkspaceProjectsConvention =
  | ExplicitPathProjectConvention
  | ParentDirectoryProjectConvention
  | string;

export type WorkspaceProjectDefined =
  | ({
      readonly glob: string;
      readonly type: "explicit";
    } & Partial<ExplicitPathProjectConvention>)
  | ({
      readonly glob: string;
      readonly type: "glob";
    } & Partial<ParentDirectoryProjectConvention>);
