name: CI
on:
  push:
    branches:
      - main
  pull_request: {}
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20.7.0
          cache: yarn
      - run: yarn install --immutable
      - run: ./node_modules/@moonrepo/cli/moon ci
        env:
          MOON_TOOLCHAIN_FORCE_GLOBALS: "true"
