name: Moon CI
on:
  push:
    branches:
      - main
  pull_request: {}
jobs:
  ci:
    name: Moon CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/moon-ci-setup
