name: Moon CI
on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_call:
    inputs:
      registry-url:
        type: string
        required: false
jobs:
  ci:
    name: Moon CI
    runs-on: ubuntu-latest
    env:
      MOON_TOOLCHAIN_FORCE_GLOBALS: "true"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: yarn
          registry-url: ${{ inputs.registry-url || 'https://registry.npmjs.org/' }}
      - uses: oven-sh/setup-bun@v1
      - run: yarn install --immutable
      - run: ./node_modules/.bin/moon ci :build
