on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}
      paths_released: ${{ steps.release-please.outputs.paths_released }}
    steps:
      - id: release-please
        uses: niieani/release-please-action@use-fork
        with:
          config-file: .config/release-please/config.json
          manifest-file: .config/release-please/manifest.json
  release:
    runs-on: ubuntu-latest
    needs:
      - release-please
    if: ${{ needs.release-please.outputs.releases_created == 'true' }}
    steps:
      - uses: ./.github/workflows/moon-ci.yml
      - run: yarn run condu before-release --ci ${{ join( fromJSON(
          needs.release-please.outputs.paths_released ), ' ' ) }}
      - run: ./node_modules/.bin/lerna publish from-package --no-git-reset --no-push
          --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
